HADOOP_EXEC=/opt/hadoop-2.7.1/sbin/
SCRIPT_DIR = /scripts/

run-wordcount-java:
	           # cp WordCount.java /scripts/
	           # cp run-app.sh /scripts/
	           cd $(SCRIPT_DIR)
	           sh run-app.sh 
	  

		
