HADOOP_EXEC=/opt/hadoop-2.7.1/sbin/ 
SCRIPT_DIR =/scripts/ 
run-java:
	# cp WordCount.java /scripts/ cp run-app.sh /scripts/
	cd $(SCRIPT_DIR)
	sh run-java-app.sh
	  
run-python:
	# cp WordCount.java /scripts/ cp run-app.sh /scripts/
	cd $(SCRIPT_DIR)
	sh run-python-app.sh
