swagger: "2.0"
info: 
  version: "0.0.1"
  title: "cpuinfo"
  description: "A simple service to get the file replication info as an example of using swagger-2.0 specification and codegen"
  termsOfService: "http://swagger.io/terms/"
  contact: 
    name: "Cloudmesh REST Service Replica"
  license: 
    name: "Apache"
host: "localhost:8080"
basePath: "/file_sample"
schemes: 
  - "http"
consumes: 
  - "application/json"
produces: 
  - "application/json"
paths: 
  /replica:
    get: 
      description: "Return file replication info of the originating server"
      produces: 
        - "application/json"
      responses: 
        "200":
          description: "Relica information of the file"
          schema: 
            $ref: "#/definitions/CPU"
definitions:
  CPU:
    type: "object"
    required: 
      - "model"
    properties: 
      model:
        type: "string"
