---
swagger: "2.0"
info:
  description: "A simple service to get Key Value Store using swagger-2.0 specification\
    \ and codegen"
  version: "0.0.1"
  title: "cpuinfo"
  termsOfService: "http://swagger.io/terms/"
  contact:
    name: "Firestore Service Example"
  license:
    name: "Apache"
host: "localhost:8080"
basePath: "/api"
schemes:
- "http"
consumes:
- "application/json"
produces:
- "application/json"
paths:
  /keyvalstore:
    get:
      description: "Returns key value store object"
      operationId: "keyvalstore_get"
      produces:
      - "application/json"
      parameters: []
      responses:
        200:
          description: "Key Value Store"
          schema:
            $ref: "#/definitions/User"
      x-swagger-router-controller: "swagger_server.controllers.default_controller"
definitions:
  User:
    type: "object"
    required:
    - "model"
    properties:
      model:
        type: "string"
    example:
      model: "model"
